// Auto-generated svgId thumbnail index
// Generated on 2025-09-26T13:16:08.180Z

export const svgIdThumbnails: Record<string, any> = {
  latissimus_dorsi: require("./latissimus_dorsi.webp"),
  serratus_anterior: require("./serratus_anterior.webp"),
  tensor_fasciae_latae: require("./tensor_fasciae_latae.webp"),
  rhomboid_muscles: require("./rhomboid_muscles.webp"),
  adductor_longus_and_pectineus: require("./adductor_longus_and_pectineus.webp"),
  flexor_carpi_radialis: require("./flexor_carpi_radialis.webp"),
  vastus_lateralis: require("./vastus_lateralis.webp"),
  deltoids: require("./deltoids.webp"),
  peroneus_longus: require("./peroneus_longus.webp"),
  sartorius: require("./sartorius.webp"),
  semitendinosus: require("./semitendinosus.webp"),
  biceps_femoris: require("./biceps_femoris.webp"),
  gluteus_maximus: require("./gluteus_maximus.webp"),
  teres_major: require("./teres_major.webp"),
  extensor_carpi_radialis: require("./extensor_carpi_radialis.webp"),
  rectus_femoris: require("./rectus_femoris.webp"),
  brachialis: require("./brachialis.webp"),
  sternocleidomastoid: require("./sternocleidomastoid.webp"),
  brachioradialis: require("./brachioradialis.webp"),
  rectus_abdominis: require("./rectus_abdominis.webp"),
  pectoralis_major: require("./pectoralis_major.webp"),
  gluteus_medius: require("./gluteus_medius.webp"),
  triceps_brachii: require("./triceps_brachii.webp"),
  soleus: require("./soleus.webp"),
  lower_trapezius: require("./lower_trapezius.webp"),
  infraspinatus: require("./infraspinatus.webp"),
  vastus_medialis: require("./vastus_medialis.webp"),
  adductor_magnus: require("./adductor_magnus.webp"),
  trapezius: require("./trapezius.webp"),
  biceps_brachii: require("./biceps_brachii.webp"),
  gracilis: require("./gracilis.webp"),
  flexor_carpi_ulnaris: require("./flexor_carpi_ulnaris.webp"),
  external_obliques: require("./external_obliques.webp"),
  gastrocnemius: require("./gastrocnemius.webp"),
  erector_spinae: require("./erector_spinae.webp"),
};
